from .wireframe_cube import WireframeCube
from .cube_uv_top import CubeUVTop
from .ico_sphere import IcoSphere
from .sky_dome import SkyDome
from .diamond import Diamond
from .sphere import Sphere
from .circle import Circle
from .plane import Plane
from .cube import Cube
from .quad import Quad
